description: |-
  Section holding all file sources configurations.
type: array
default: []
items:
  discriminator:
    propertyName: kind
    mapping:
      fixed: 'fileSources/fixedFileSourceConfig.yaml'
      delimited: 'fileSources/delimitedFileSourceConfig.yaml'
      avro: 'fileSources/avroFileSourceConfig.yaml'
      orc: 'fileSources/orcFileSourceConfig.yaml'
      parquet: 'fileSources/parquetFileSourceConfig.yaml'
  oneOf:
    - $ref: 'fileSources/fixedFileSourceConfig.yaml'
    - $ref: 'fileSources/delimitedFileSourceConfig.yaml'
    - $ref: 'fileSources/avroFileSourceConfig.yaml'
    - $ref: 'fileSources/orcFileSourceConfig.yaml'
    - $ref: 'fileSources/parquetFileSourceConfig.yaml'
