site_name: Checkita Data Quality
site_url: https://raiffeisen-dgtl.github.io/checkita-data-quality/

# Repository
repo_name: checkita-data-quality
repo_url: https://github.com/Raiffeisen-DGTL/checkita-data-quality

theme:
  name: material
  palette:
    scheme: slate
    primary: yellow
  logo: logo/logo.png
  favicon: logo/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow
    - toc.integrate

markdown_extensions:
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
   
plugins:
  - search
  - swagger-ui-tag
              
nav:
  - Home: index.md
  - Application Setup:
      - 01-application-setup/index.md
      - 01-application-setup/01-ApplicationSettings.md
      - 01-application-setup/02-ApplicationSubmit.md
      - 01-application-setup/03-ResultsStorage.md
      - 01-application-setup/04-APIServer.md
  - General Information:
      - 02-general-information/index.md
      - 02-general-information/01-WorkingWithDateTime.md
      - 02-general-information/02-EnvironmentAndExtraVariables.md
      - 02-general-information/03-StatusModel.md
      - 02-general-information/04-ErrorCollection.md
      - 02-general-information/05-StreamingMode.md
      - 02-general-information/06-MetricSQLEquivalency.md
      - 02-general-information/07-MetricCalculatorEngines.md
  - Job Configuration:
      - 03-job-configuration/index.md
      - 03-job-configuration/01-Connections.md
      - 03-job-configuration/02-Schemas.md
      - 03-job-configuration/03-Sources.md
      - 03-job-configuration/04-Streams.md
      - 03-job-configuration/05-VirtualSources.md
      - 03-job-configuration/06-VirtualStreams.md
      - 03-job-configuration/07-LoadChecks.md
      - 03-job-configuration/08-Metrics.md
      - 03-job-configuration/09-Checks.md
      - 03-job-configuration/10-Targets.md
      - 03-job-configuration/11-FileOutputs.md
      - 03-job-configuration/12-JobConfigExample.md
  - Changelog: changelog/CHANGELOG.md
  - Contribution:
      - contribution/index.md
      - contribution/code-of-conduct.md
      - contribution/contribution.md
  - Scala API Doc: api/index.html
  - Swagger Doc: swagger/index.md