type: object
properties:
  windowBy:
    type: string
    description: |-
      Source of timestamp used to assign records to a particular streaming windows and also 
      to skip "late" records. Applicable only for streaming jobs!
      There are following options supported:
        * `processingTime` - Uses current timestamp at the moment when Spark processes record.
        * `eventTime` - Mostly applicable to kafka sources. Uses column with name timestamp to retrieve time value from. 
          This column must be of Timestamp type.
        * custom(<columnName>) - Uses arbitrary user-defined column to retrieve time value from.
          Specified column must be of Timestamp type. In addition, an SQL expressions are supported. 
          An expression should also evaluate to value of Timestamp type. 
          For example: `custom(value.createdAt)` - the time value for a record will be retrieved from message value's 
          field with name createdAt.
    default: processingTime
    enum:
      - processingTime
      - eventTime
      - custom(<columnName>)