allOf:
  - $ref: 'baseConnectionConfig.yaml'
  - type: object
    description: Connection configuration to PostgreSQL database
    required:
      - url
    properties:
      url:
        type: string
        description: |-
          Connection URL. Should contain host, port and name of database. 
          In addition, extra parameters can be supplied in connection URL if required. 
          ***Connection protocol must not be specified.***
        example: postgre1.db.com:5432/public
      username:
        type: string
        description: Username used to connect to PostgreSQL database if required.
        example: someUser
      password:
        type: string
        description: Password used to connect to PostgreSQL database if required.
        example: somePassword!
