type: object
required:
  - params
properties:
  params:
    type: object
    description: Get percentile metric parameters.
    required:
      - target
    properties:
      accuracyError:
        type: number
        description: Accuracy error for estimating metric value.
        default: 0.01
        example: 0.005
      target:
        type: number
        description: A number in the interval `[0, 1]` corresponding to the quantile that need to be calculated.
        example: 0.15
    