description: |-
  Section holding all file sources configurations.
type: array
default: []
items:
  discriminator:
    propertyName: kind
    mapping:
      fixed: 'fixedFileSourceConfig.yaml'
      delimited: 'delimitedFileSourceConfig.yaml'
      avro: 'avroFileSourceConfig.yaml'
      orc: 'orcFileSourceConfig.yaml'
      parquet: 'parquetFileSourceConfig.yaml'
  oneOf:
    - $ref: 'fixedFileSourceConfig.yaml'
    - $ref: 'delimitedFileSourceConfig.yaml'
    - $ref: 'avroFileSourceConfig.yaml'
    - $ref: 'orcFileSourceConfig.yaml'
    - $ref: 'parquetFileSourceConfig.yaml'
