type: object
required:
  - id
  - formula
properties:
  id:
    type: string
    description: Composed metric ID
    example: derivative_metric
  description:
    type: string
    description: Optional. Composed metric description
    example: Derivative metric to compute percentage of rows that failed a criteria.
  formula:
    type: string
    description: Formula to calculate composed metric
    example: "{{ failed_criteria_metric }} / {{ row_count_metric }} * 100"
  metadata:
    type: array
    description: Optional list of arbitrary user-defined metadata parameters specific to this composed metric
    items:
      type: string
      description: Metadata parameter string in format of `param.name=param.value`
    default: [ ]
