type: object
required:
  - params
properties:
  params:
    type: object
    description: Metric parameters for number compare
    required:
      - compareValue
    properties:
      compareValue:
        type: number
        description: Number to compare with.
        example: 2.718
      includeBound:
        type: boolean
        description: Specifies whether to include `compareValue` in the range for comparison.
        default: false
        example: true
    