type: object
required:
  - params
properties:
  params:
    type: object
    description: Metric parameters for number interval definition.
    required:
      - lowerCompareValue
      - upperCompareValue
    properties:
      lowerCompareValue:
        type: number
        description: The lower bound of the interval.
        example: 1.618
      upperCompareValue:
        type: number
        description: The upper bound of the interval.
        example: 3.14
      includeBound:
        type: boolean
        description: Specifies whether to include interval bounds in the range for comparison.
        default: false
        example: true
    