type: object
required:
  - params
properties:
  params:
    type: object
    description: Number domain metric parameters
    required:
      - domain
    properties:
      domain:
        type: array
        description: List of number values
        example:
          - 3.14
          - 1.618
        items:
          type: number
          description: Number value
    