type: object
required:
  - params
properties:
  params:
    type: object
    description: Regex metric parameters.
    required:
      - regex
    properties:
      regex:
        type: string
        description: Regular expression
        example: "^foo$"
    