description: |-
  Section holding configuration of various boolean switchers and single-value parameters
  that controls different aspects of data quality job execution.
  If this section is missing in configuration file then default values are used
  for all parameters within.
type: object
properties:
  allowSqlQueries:
    type: boolean
    description: Enables usage arbitrary SQL queries in data quality job configuration
    default: false
    example: true
  allowNotifications:
    type: boolean
    description: Enables notifications to be sent from DQ application
    default: false
    example: true
  aggregatedKafkaOutput:
    type: boolean
    description: Enables sending aggregates messages for Kafka Targets (one per each target type)
    default: false
    example: true
  enableCaseSensitivity:
    type: boolean
    description: Enable columns case sensitivity. Controls column names comparison and lookup
    default: false
    example: true
  errorDumpSize:
    type: integer
    description: Maximum number of errors to be collected per single metric
    default: 10000
    example: 100
  outputRepartition:
    type: integer
    description: Sets the number of partitions when writing outputs
    default: 1
    example: 4
  metricEngineAPI:
    type: string
    description: |-
      Sets engine to be used for regular metric processing: RDD- or DF-engines are
      available. It is recommended to use DF-engine for batch applications while streaming applications support only
      RDD-engine.
    default: rdd
    example: df
    enum:
      - rdd
      - df