type: object
required:
  - expr
properties:
  expr:
    type: array
    description: Sequence of filter SQL expressions applied to parent source.
    example:
      - 'id IS NOT NULL'
    items:
      type: string
      description: Filter SQL expression

      
    