description: |-
  Load checks are the special type of checks that are distinguished from other checks as they are applied not to results
  of metrics computation but to sources metadata. Another key feature of load checks is that they are run prior to 
  actual data loading from the sources, made possible due to Spark's lazy evaluation mechanisms: 
  sources are, essentially, Spark dataframes and load checks are used to verify their metadata.
type: array
items:
  oneOf:
    - title: minColumnNum
      allOf:
        - $ref: 'loadChecks/baseLoadCheckConfig.yaml'
        - $ref: 'loadChecks/minColumnLoadCheckConfig.yaml'
    - title: exactColumnNum
      allOf:
        - $ref: 'loadChecks/baseLoadCheckConfig.yaml'
        - $ref: 'loadChecks/exactColumnLoadCheckConfig.yaml'
    - title: columnsExist
      allOf:
        - $ref: 'loadChecks/baseLoadCheckConfig.yaml'
        - $ref: 'loadChecks/columnsExistLoadCheckConfig.yaml'
    - title: schemaMatch
      allOf:
        - $ref: 'loadChecks/baseLoadCheckConfig.yaml'
        - $ref: 'loadChecks/schemaMatchLoadCheckConfig.yaml'
