description: |-
  Section holding all sources configurations.
  Reading sources is a critical part of a Data Quality job in Checkita. During execution, Checkita reads all sources into Spark DataFrames, 
  which are then processed to calculate metrics and perform quality checks. Additionally, dataframes' metadata is used to perform load checks 
  ensuring the source has the expected structure. Checkita supports reading from file systems, object storage (HDFS, S3), Hive catalogs, RDBMS, 
  Kafka, Greenplum, and custom sources.
type: object
properties:
  file:
    description: Section holding all file sources configurations.
    type: array
    default: [ ]
    items:
      oneOf:
        - title: fixed
          allOf:
            - $ref: 'sources/base/baseSourceConfig.yaml'
            - $ref: 'sources/base/baseFileSourceConfig.yaml'
            - $ref: 'sources/base/fixedFileSourceConfig.yaml'
        - title: delimited
          allOf:
            - $ref: 'sources/base/baseSourceConfig.yaml'
            - $ref: 'sources/base/baseFileSourceConfig.yaml'
            - $ref: 'sources/base/delimitedFileSourceConfig.yaml'
        - title: avro
          allOf:
            - $ref: 'sources/base/baseSourceConfig.yaml'
            - $ref: 'sources/base/baseFileSourceConfig.yaml'
            - $ref: 'sources/base/avroFileSourceConfig.yaml'
        - title: orc
          allOf:
            - $ref: 'sources/base/baseSourceConfig.yaml'
            - $ref: 'sources/base/baseFileSourceConfig.yaml'
        - title: parquet
          allOf:
            - $ref: 'sources/base/baseSourceConfig.yaml'
            - $ref: 'sources/base/baseFileSourceConfig.yaml'
  hive:
    description: Section holding all hive sources configurations.
    type: array
    default: [ ]
    items:
      allOf:
        - $ref: 'sources/base/baseSourceConfig.yaml'
        - $ref: 'sources/base/hiveSourceConfig.yaml'
  table:
    description: Section holding all table sources configurations.
    type: array
    default: [ ]
    items:
      allOf:
        - $ref: 'sources/base/baseSourceConfig.yaml'
        - $ref: 'sources/base/tableSourceConfig.yaml'
  kafka:
    description: Section holding all kafka sources configurations.
    type: array
    default: [ ]
    items:
      allOf:
        - $ref: 'sources/base/baseSourceConfig.yaml'
        - $ref: 'sources/base/kafkaSourceConfig.yaml'
  greenplum:
    description: Section holding all greenplum sources configurations.
    type: array
    default: [ ]
    items:
      allOf:
        - $ref: 'sources/base/baseSourceConfig.yaml'
        - $ref: 'sources/base/greenplumSourceConfig.yaml'
  custom:
    description: Section holding all custom sources configurations.
    type: array
    default: [ ]
    items:
      allOf:
        - $ref: 'sources/base/baseSourceConfig.yaml'
        - $ref: 'sources/base/customSourceConfig.yaml'