name: Build and Test Project at Main

on:
  push:
    branches:
      - main

permissions:
  contents: read
    
jobs:
  build_n_test:
    strategy:
      matrix:
        version: ["2.4.0", "3.0.3", "3.1.3", "3.2.4", "3.3.3", "3.4.1", "3.5.0"] # spark versions
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Set JVM Options  # Checkita uses some compile-heavy libraries.
        run: |
          echo "-Xmx2G" > .jvmopts
          echo "-Xms1G" >> .jvmopts
          echo "-Xss100m" >> .jvmopts
      - name: Compile and Test for Spark ${{ matrix.version }}
        run: sbt -DASSY_MODE=WITHSPARK -DSPARK_VERSION=${{ matrix.version }} checkita-core/clean checkita-core/compile checkita-core/test