name: Pull Request - Build and Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

permissions:
    contents: read

jobs:
  build_n_test:
    strategy:
      matrix:
        scala-version: ['2.12', '2.13']
        spark-version: ["3.2.0", "3.2.4", "3.3.3", "3.4.1", "3.5.1"]
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Set JVM Options  # Checkita uses some compile-heavy libraries.
        run: |
          echo "-Xmx2G" > .jvmopts
          echo "-Xms1G" >> .jvmopts
          echo "-Xss100m" >> .jvmopts
      - name: Compile and Test CORE for Scala ${{ matrix.scala-version }} and Spark ${{ matrix.spark-version }}
        run: sbt -DASSY_MODE=WITHSPARK -DSCALA_VERSION=${{ matrix.scala-version }} -DSPARK_VERSION=${{ matrix.spark-version }} -Duser.timezone="Europe/Moscow" checkita-core/clean checkita-core/compile checkita-core/test
      - name: Compile API for Scala ${{ matrix.scala-version }} and Spark ${{ matrix.spark-version }}
        if: ${{ ! startsWith(matrix.spark-version, '3.2')}}
        run: sbt -DASSY_MODE=WITHSPARK -DSCALA_VERSION=${{ matrix.scala-version }} -DSPARK_VERSION=${{ matrix.spark-version }} -Duser.timezone="Europe/Moscow" checkita-api/clean checkita-api/compile

