name: Pull Request - Verify Title
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  validate_title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}