name: Checkita Release

on:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  publish:
    strategy:
      matrix:
        scala-version: ['2.12', '2.13']
        spark-version: ["3.2.0", "3.2.1", "3.2.2", "3.2.3", "3.2.4", "3.3.0", "3.3.1", "3.3.2", "3.3.3", "3.3.4", "3.4.0", "3.4.1", "3.4.2", "3.4.3", "3.5.0", "3.5.1"]
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Set JVM Options  # Checkita uses some compile-heavy libraries.
        run: |
          echo "-Xmx2G" > .jvmopts
          echo "-Xms1G" >> .jvmopts
          echo "-Xss100m" >> .jvmopts
      - name: Set GPG Key
        run: gpg --list-keys # todo: need actual gpg keys flow
      - name: Set SBT Credentials
        run: |
          echo "realm=Sonatype Nexus Repository Manager" > ~/.sbt/.credentials
          echo "host=s01.oss.sonatype.org" >> ~/.sbt/.credentials
          echo "user=$ST_USER" >> ~/.sbt/.credentials
          echo "password=$ST_PASSWORD" >> ~/.sbt/.credentials
        env:
          ST_USER: ${{ secrets.SONATYPE_USER }}
          ST_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      - name: Compile and Publish for Scala ${{ matrix.scala-version }} and Spark ${{ matrix.spark-version }}
        run: |
          sbt \
            -DASSY_MODE=WITHSPARK \
            -DSCALA_VERSION=$SCALA_VER \
            -DSPARK_VERSION=$SPARK_VER \
            -Duser.timezone="Europe/Moscow" \
            -DPUBLISH_REALM=$REALM \
            -DPUBLISH_URL=$URL \
            -DPKG_TYPE=$PKG \
            checkita-core/clean \
            checkita-core/compile \
            checkita-core/publishSigned
        env:
          SCALA_VER: ${{ matrix.scala-version }}
          SPARK_VER: ${{ matrix.spark-version }}
          REALM: Sonatype
          URL: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2
          PKG: RELEASE
      