name: Checkita Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CIBAA_TEAM_USER_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec
      - run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.CIBAA_TEAM_USER_TOKEN }}
  pages: # deploy docs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout latest release tags
        run: |
          export LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $LATEST_TAG
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Generate ScalaDoc
        run: sbt -DSPARK_VERSION=3.5.0 checkita-core/doc
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-static-i18n
      - run: mkdocs gh-deploy --force